
export const pipeData = [
  [
    {
      AcceptanceCriteriaAPI: 'Steel to be used in the manufacture of the pipes shall be made in basic oxygen or electric arc furnace. The steel shall be continuous cast and fully killed and made according to fine grain practice. The strip shall not contain any repair welds.',
      AcceptanceCriteriaExtracted: 'The seam annealed area shall be cooled \nat an appropriate rate to produce a refined grain microstructure (grain size \n8 or finer).',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: 'API 5L CL 8.38.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coiltfp',
      TestingFrequencyExtracted: '',
      TPI: 'R',
      WorkDescription: 'Steel Coils',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: '',
      AcceptanceCriteriaExtracted: 'Internal slab quality will be measured by macro etch tests rated using the Mannesmann Rating System. For sulfur contents less than or equal to 0.007% the acceptable etching techniques are hot HCL acid, ammonium persulfate or Steltech acid etching. Cold acid etching is not suitable for revealing inclusions. A minimum of one slab macro-etch test shall be performed from the first heat (manufacturing run) of each sequence and every 4th heat thereafter for each casting sequence. Macro- etching shall cover the full width and cross section of the slab. The macro-etched surfaces shall be rated in accordance with the 1-5 Mannesmann Scale and meet the following standards: \n Inclusions - 2 maximum \n Alumina Clouds - 2 maximum \n Transverse Internal Cracks - 2 maximum \n Center Segregation - 2 maximum \n Corner Cracks - 2 maximum \n Macro-etch photographs and/or records and other mill control tests of the slab cross section shall be made available to Purchaser and Company representative for inspection at time of testing.',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: '',
      ReferenceStandardExtracted: 'Client Spec Cl. 4.8.2',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: '',
      TestingFrequencyExtracted: 'A minimum of 3 heats from each casting sequence shall be macro-etch tested or each heat if casting sequence less than 3 heats.',
      TPI: 'R',
      WorkDescription: 'Slab macro-etch',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Coil Width',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: '',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Thickness',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Annealing Temperature: Minimum 1600°F so as tosimulate a normalizing heat treatment. More changes.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe(100% weld area)',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Seam Annealing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per approved work instruction WTL/HFW/QC/WI/12',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Approved work instruction',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'On Line UT (Optional)',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Aim A.9.5, adjust as needed to meet A.9.5 after hydro',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.9.1',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Random',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Pipe Sizing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'End load compensation is not used.\n If distortion occurs QA/QC will investigate the cause of the distortion.\n Pressure gauge shall be calibrated or checked against an isolated mater gauge at the time of starting of production, after all hydrostatic test bursts and at least once a week during production.\n The tester shall be equipped with a recording gauge that can record the test pressure and the test duration for each length of pipe.\n The test pressure measuring device shall be calibrated by means of a dead-weight tester no more than 4 months prior to each use.',
      AcceptanceCriteriaExtracted: 'Min. Pressure = 2*S*t/D where S = 95% SMYS Duration 10 seconds ',
      AcceptedCriteriaTable: [
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X70M',
          MinP: '3580',
          Hold: '10 sec'
        },
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X65M',
          MinP: '3580',
          Hold: '10 sec'
        }
      ],
      Documents: 'Graph chart showing pressure & holding time for each pipe And test report',
      ReferenceStandardAPI: 'API 5L CL 10.2.6',
      ReferenceStandardExtracted: 'CL 10.2.6',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Hydrostatic Test',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Bevel angle = 30° (+5°, -0°) Root face = 1/16” ± 1/32 (1.6mm±0.8mm)',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual  &Dimension report',
      ReferenceStandardAPI: 'API 5L CL9.12.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plainendpipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Beveling',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Reference standard shall have the same thickness, same material and same geometry as the pipe being inspected& as per work instruction for offline UT of weld, WTL/HFW/QC/WI/10.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Cal. Report / graph',
      ReferenceStandardAPI: 'API 5L Annex E.5.2, E.5.3',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Beginning of shift, at least once during an 8 hour shift, before any planned shutdown, at the end of the production, and any time UT machine is interrupted / repaired',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'UT calibration standard',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Weld area, HAZ and mid-wall shall be inspected for longitudinal imperfections. Any signal exceeding alarm threshold limit shall be marked automatically by the marking system of equipment and shall be tested by manual UT. Also Any signal exceeding alarm threshold limit shall be recorded in a chart graph automatically by system. For any weld defect, as per client spec and work instruction for offline UT of the weld, WTL/HFW/QC/WI/10',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'UT report',
      ReferenceStandardAPI: 'API 5L Annex E.5, E.5.5',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '100% weld seam of each pipe(except untested length due to thel imitation of the AUT system)',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Weld Seam Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'For any weld area longitudinal defects as per WI for pipe end ultrasonic testing, WTL/HFW/QC/WI/09. Any indication found greater than acceptance limit in pipe shall be cut-off or rejected',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'MUT report',
      ReferenceStandardAPI: 'API 5L Annex E.3.2.1, E.3.2.3, E.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Each pipe weld length untested by AUT & indications marked by AUT.',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Manual Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Four reading shall be taken ≈ 90° apart around the circumference of each end of the pipe. No one reading shall exceed 25 gauss (3.5 mT) per pipe end when measured with a Hall-effect gauss meter or equivalent values when measured with another type of instrument',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Test report',
      ReferenceStandardAPI: 'API 5L Annex E.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '1 pipes / 4hour shift',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Residual Magnetism',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'The external & internal surfaces of the pipe shall be presented for final visual inspection free of oil, grease, lubricant, flux, loose mill scale or other foreign matter Visual inspection shall include, but not be limited to, the following:\n The entire external surface by an inspector walking the full length of the pipe.\n The internal surface from the pipe ends by an inspector using inspection lamps.\n The pipe ends.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual & Dimension Report',
      ReferenceStandard: 'API 5L CL 10.2.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'WORKMANSHIP, VISUAL INSPECTION AND REPAIR OF DEFECTS',
      TestingFrequency: 'Each pipe inside & outside, pipe ends',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Visual Inspection',
      WTL: 'H',
      Comment: ''
    }
  ],
  [
    {
      AcceptanceCriteriaAPI: 'Steel to be used in the manufacture of the pipes shall be made in basic oxygen or electric arc furnace. The steel shall be continuous cast and fully killed and made according to fine grain practice. The strip shall not contain any repair welds.',
      AcceptanceCriteriaExtracted: 'The seam annealed area shall be cooled \nat an appropriate rate to produce a refined grain microstructure (grain size \n8 or finer).',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: 'API 5L CL 8.38.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coiltfp',
      TestingFrequencyExtracted: '',
      TPI: 'R',
      WorkDescription: 'Steel Coils',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: '',
      AcceptanceCriteriaExtracted: 'Internal slab quality will be measured by macro etch tests rated using the Mannesmann Rating System. For sulfur contents less than or equal to 0.007% the acceptable etching techniques are hot HCL acid, ammonium persulfate or Steltech acid etching. Cold acid etching is not suitable for revealing inclusions. A minimum of one slab macro-etch test shall be performed from the first heat (manufacturing run) of each sequence and every 4th heat thereafter for each casting sequence. Macro- etching shall cover the full width and cross section of the slab. The macro-etched surfaces shall be rated in accordance with the 1-5 Mannesmann Scale and meet the following standards: \n Inclusions - 2 maximum \n Alumina Clouds - 2 maximum \n Transverse Internal Cracks - 2 maximum \n Center Segregation - 2 maximum \n Corner Cracks - 2 maximum \n Macro-etch photographs and/or records and other mill control tests of the slab cross section shall be made available to Purchaser and Company representative for inspection at time of testing.',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: '',
      ReferenceStandardExtracted: 'Client Spec Cl. 4.8.2',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: '',
      TestingFrequencyExtracted: 'A minimum of 3 heats from each casting sequence shall be macro-etch tested or each heat if casting sequence less than 3 heats.',
      TPI: 'R',
      WorkDescription: 'Slab macro-etch',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Coil Width',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: '',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Thickness',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Annealing Temperature: Minimum 1600°F so as tosimulate a normalizing heat treatment. More changes.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe(100% weld area)',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Seam Annealing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per approved work instruction WTL/HFW/QC/WI/12',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Approved work instruction',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'On Line UT (Optional)',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Aim A.9.5, adjust as needed to meet A.9.5 after hydro',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.9.1',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Random',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Pipe Sizing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'End load compensation is not used.\n If distortion occurs QA/QC will investigate the cause of the distortion.\n Pressure gauge shall be calibrated or checked against an isolated mater gauge at the time of starting of production, after all hydrostatic test bursts and at least once a week during production.\n The tester shall be equipped with a recording gauge that can record the test pressure and the test duration for each length of pipe.\n The test pressure measuring device shall be calibrated by means of a dead-weight tester no more than 4 months prior to each use.',
      AcceptanceCriteriaExtracted: 'Min. Pressure = 2*S*t/D where S = 95% SMYS Duration 10 seconds ',
      AcceptedCriteriaTable: [
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X70M',
          MinP: '3580',
          Hold: '10 sec'
        },
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X65M',
          MinP: '3580',
          Hold: '10 sec'
        }
      ],
      Documents: 'Graph chart showing pressure & holding time for each pipe And test report',
      ReferenceStandardAPI: 'API 5L CL 10.2.6',
      ReferenceStandardExtracted: 'CL 10.2.6',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Hydrostatic Test',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Bevel angle = 30° (+5°, -0°) Root face = 1/16” ± 1/32 (1.6mm±0.8mm)',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual  &Dimension report',
      ReferenceStandardAPI: 'API 5L CL9.12.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plainendpipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Beveling',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Reference standard shall have the same thickness, same material and same geometry as the pipe being inspected& as per work instruction for offline UT of weld, WTL/HFW/QC/WI/10.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Cal. Report / graph',
      ReferenceStandardAPI: 'API 5L Annex E.5.2, E.5.3',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Beginning of shift, at least once during an 8 hour shift, before any planned shutdown, at the end of the production, and any time UT machine is interrupted / repaired',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'UT calibration standard',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Weld area, HAZ and mid-wall shall be inspected for longitudinal imperfections. Any signal exceeding alarm threshold limit shall be marked automatically by the marking system of equipment and shall be tested by manual UT. Also Any signal exceeding alarm threshold limit shall be recorded in a chart graph automatically by system. For any weld defect, as per client spec and work instruction for offline UT of the weld, WTL/HFW/QC/WI/10',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'UT report',
      ReferenceStandardAPI: 'API 5L Annex E.5, E.5.5',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '100% weld seam of each pipe(except untested length due to thel imitation of the AUT system)',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Weld Seam Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'For any weld area longitudinal defects as per WI for pipe end ultrasonic testing, WTL/HFW/QC/WI/09. Any indication found greater than acceptance limit in pipe shall be cut-off or rejected',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'MUT report',
      ReferenceStandardAPI: 'API 5L Annex E.3.2.1, E.3.2.3, E.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Each pipe weld length untested by AUT & indications marked by AUT.',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Manual Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Four reading shall be taken ≈ 90° apart around the circumference of each end of the pipe. No one reading shall exceed 25 gauss (3.5 mT) per pipe end when measured with a Hall-effect gauss meter or equivalent values when measured with another type of instrument',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Test report',
      ReferenceStandardAPI: 'API 5L Annex E.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '1 pipes / 4hour shift',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Residual Magnetism',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'The external & internal surfaces of the pipe shall be presented for final visual inspection free of oil, grease, lubricant, flux, loose mill scale or other foreign matter Visual inspection shall include, but not be limited to, the following:\n The entire external surface by an inspector walking the full length of the pipe.\n The internal surface from the pipe ends by an inspector using inspection lamps.\n The pipe ends.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual & Dimension Report',
      ReferenceStandard: 'API 5L CL 10.2.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'WORKMANSHIP, VISUAL INSPECTION AND REPAIR OF DEFECTS',
      TestingFrequency: 'Each pipe inside & outside, pipe ends',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Visual Inspection',
      WTL: 'H',
      Comment: ''
    }
  ],
  [
    {
      AcceptanceCriteriaAPI: 'Steel to be used in the manufacture of the pipes shall be made in basic oxygen or electric arc furnace. The steel shall be continuous cast and fully killed and made according to fine grain practice. The strip shall not contain any repair welds.',
      AcceptanceCriteriaExtracted: 'The seam annealed area shall be cooled \nat an appropriate rate to produce a refined grain microstructure (grain size \n8 or finer).',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: 'API 5L CL 8.38.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coiltfp',
      TestingFrequencyExtracted: '',
      TPI: 'R',
      WorkDescription: 'Steel Coils',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: '',
      AcceptanceCriteriaExtracted: 'Internal slab quality will be measured by macro etch tests rated using the Mannesmann Rating System. For sulfur contents less than or equal to 0.007% the acceptable etching techniques are hot HCL acid, ammonium persulfate or Steltech acid etching. Cold acid etching is not suitable for revealing inclusions. A minimum of one slab macro-etch test shall be performed from the first heat (manufacturing run) of each sequence and every 4th heat thereafter for each casting sequence. Macro- etching shall cover the full width and cross section of the slab. The macro-etched surfaces shall be rated in accordance with the 1-5 Mannesmann Scale and meet the following standards: \n Inclusions - 2 maximum \n Alumina Clouds - 2 maximum \n Transverse Internal Cracks - 2 maximum \n Center Segregation - 2 maximum \n Corner Cracks - 2 maximum \n Macro-etch photographs and/or records and other mill control tests of the slab cross section shall be made available to Purchaser and Company representative for inspection at time of testing.',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: '',
      ReferenceStandardExtracted: 'Client Spec Cl. 4.8.2',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: '',
      TestingFrequencyExtracted: 'A minimum of 3 heats from each casting sequence shall be macro-etch tested or each heat if casting sequence less than 3 heats.',
      TPI: 'R',
      WorkDescription: 'Slab macro-etch',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Coil Width',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: '',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Thickness',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Annealing Temperature: Minimum 1600°F so as tosimulate a normalizing heat treatment. More changes.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe(100% weld area)',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Seam Annealing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per approved work instruction WTL/HFW/QC/WI/12',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Approved work instruction',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'On Line UT (Optional)',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Aim A.9.5, adjust as needed to meet A.9.5 after hydro',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.9.1',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Random',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Pipe Sizing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'End load compensation is not used.\n If distortion occurs QA/QC will investigate the cause of the distortion.\n Pressure gauge shall be calibrated or checked against an isolated mater gauge at the time of starting of production, after all hydrostatic test bursts and at least once a week during production.\n The tester shall be equipped with a recording gauge that can record the test pressure and the test duration for each length of pipe.\n The test pressure measuring device shall be calibrated by means of a dead-weight tester no more than 4 months prior to each use.',
      AcceptanceCriteriaExtracted: 'Min. Pressure = 2*S*t/D where S = 95% SMYS Duration 10 seconds ',
      AcceptedCriteriaTable: [
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X70M',
          MinP: '3580',
          Hold: '10 sec'
        },
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X65M',
          MinP: '3580',
          Hold: '10 sec'
        }
      ],
      Documents: 'Graph chart showing pressure & holding time for each pipe And test report',
      ReferenceStandardAPI: 'API 5L CL 10.2.6',
      ReferenceStandardExtracted: 'CL 10.2.6',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Hydrostatic Test',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Bevel angle = 30° (+5°, -0°) Root face = 1/16” ± 1/32 (1.6mm±0.8mm)',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual  &Dimension report',
      ReferenceStandardAPI: 'API 5L CL9.12.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plainendpipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Beveling',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Reference standard shall have the same thickness, same material and same geometry as the pipe being inspected& as per work instruction for offline UT of weld, WTL/HFW/QC/WI/10.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Cal. Report / graph',
      ReferenceStandardAPI: 'API 5L Annex E.5.2, E.5.3',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Beginning of shift, at least once during an 8 hour shift, before any planned shutdown, at the end of the production, and any time UT machine is interrupted / repaired',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'UT calibration standard',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Weld area, HAZ and mid-wall shall be inspected for longitudinal imperfections. Any signal exceeding alarm threshold limit shall be marked automatically by the marking system of equipment and shall be tested by manual UT. Also Any signal exceeding alarm threshold limit shall be recorded in a chart graph automatically by system. For any weld defect, as per client spec and work instruction for offline UT of the weld, WTL/HFW/QC/WI/10',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'UT report',
      ReferenceStandardAPI: 'API 5L Annex E.5, E.5.5',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '100% weld seam of each pipe(except untested length due to thel imitation of the AUT system)',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Weld Seam Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'For any weld area longitudinal defects as per WI for pipe end ultrasonic testing, WTL/HFW/QC/WI/09. Any indication found greater than acceptance limit in pipe shall be cut-off or rejected',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'MUT report',
      ReferenceStandardAPI: 'API 5L Annex E.3.2.1, E.3.2.3, E.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Each pipe weld length untested by AUT & indications marked by AUT.',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Manual Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Four reading shall be taken ≈ 90° apart around the circumference of each end of the pipe. No one reading shall exceed 25 gauss (3.5 mT) per pipe end when measured with a Hall-effect gauss meter or equivalent values when measured with another type of instrument',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Test report',
      ReferenceStandardAPI: 'API 5L Annex E.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '1 pipes / 4hour shift',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Residual Magnetism',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'The external & internal surfaces of the pipe shall be presented for final visual inspection free of oil, grease, lubricant, flux, loose mill scale or other foreign matter Visual inspection shall include, but not be limited to, the following:\n The entire external surface by an inspector walking the full length of the pipe.\n The internal surface from the pipe ends by an inspector using inspection lamps.\n The pipe ends.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual & Dimension Report',
      ReferenceStandard: 'API 5L CL 10.2.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'WORKMANSHIP, VISUAL INSPECTION AND REPAIR OF DEFECTS',
      TestingFrequency: 'Each pipe inside & outside, pipe ends',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Visual Inspection',
      WTL: 'H',
      Comment: ''
    }
  ]

]

export const coatingData = [
  [
    {
      AcceptanceCriteriaAPI: 'Steel to be used in the manufacture of the pipes shall be made in basic oxygen or electric arc furnace. The steel shall be continuous cast and fully killed and made according to fine grain practice. The strip shall not contain any repair welds.',
      AcceptanceCriteriaExtracted: 'The seam annealed area shall be cooled \nat an appropriate rate to produce a refined grain microstructure (grain size \n8 or finer).',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: 'API 5L CL 8.38.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coiltfp',
      TestingFrequencyExtracted: '',
      TPI: 'R',
      WorkDescription: 'Steel Coils',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: '',
      AcceptanceCriteriaExtracted: 'Internal slab quality will be measured by macro etch tests rated using the Mannesmann Rating System. For sulfur contents less than or equal to 0.007% the acceptable etching techniques are hot HCL acid, ammonium persulfate or Steltech acid etching. Cold acid etching is not suitable for revealing inclusions. A minimum of one slab macro-etch test shall be performed from the first heat (manufacturing run) of each sequence and every 4th heat thereafter for each casting sequence. Macro- etching shall cover the full width and cross section of the slab. The macro-etched surfaces shall be rated in accordance with the 1-5 Mannesmann Scale and meet the following standards: \n Inclusions - 2 maximum \n Alumina Clouds - 2 maximum \n Transverse Internal Cracks - 2 maximum \n Center Segregation - 2 maximum \n Corner Cracks - 2 maximum \n Macro-etch photographs and/or records and other mill control tests of the slab cross section shall be made available to Purchaser and Company representative for inspection at time of testing.',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: '',
      ReferenceStandardExtracted: 'Client Spec Cl. 4.8.2',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: '',
      TestingFrequencyExtracted: 'A minimum of 3 heats from each casting sequence shall be macro-etch tested or each heat if casting sequence less than 3 heats.',
      TPI: 'R',
      WorkDescription: 'Slab macro-etch',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Coil Width',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: '',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Thickness',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Annealing Temperature: Minimum 1600°F so as tosimulate a normalizing heat treatment. More changes.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe(100% weld area)',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Seam Annealing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per approved work instruction WTL/HFW/QC/WI/12',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Approved work instruction',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'On Line UT (Optional)',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Aim A.9.5, adjust as needed to meet A.9.5 after hydro',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.9.1',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Random',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Pipe Sizing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'End load compensation is not used.\n If distortion occurs QA/QC will investigate the cause of the distortion.\n Pressure gauge shall be calibrated or checked against an isolated mater gauge at the time of starting of production, after all hydrostatic test bursts and at least once a week during production.\n The tester shall be equipped with a recording gauge that can record the test pressure and the test duration for each length of pipe.\n The test pressure measuring device shall be calibrated by means of a dead-weight tester no more than 4 months prior to each use.',
      AcceptanceCriteriaExtracted: 'Min. Pressure = 2*S*t/D where S = 95% SMYS Duration 10 seconds ',
      AcceptedCriteriaTable: [
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X70M',
          MinP: '3580',
          Hold: '10 sec'
        },
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X65M',
          MinP: '3580',
          Hold: '10 sec'
        }
      ],
      Documents: 'Graph chart showing pressure & holding time for each pipe And test report',
      ReferenceStandardAPI: 'API 5L CL 10.2.6',
      ReferenceStandardExtracted: 'CL 10.2.6',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Hydrostatic Test',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Bevel angle = 30° (+5°, -0°) Root face = 1/16” ± 1/32 (1.6mm±0.8mm)',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual  &Dimension report',
      ReferenceStandardAPI: 'API 5L CL9.12.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plainendpipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Beveling',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Reference standard shall have the same thickness, same material and same geometry as the pipe being inspected& as per work instruction for offline UT of weld, WTL/HFW/QC/WI/10.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Cal. Report / graph',
      ReferenceStandardAPI: 'API 5L Annex E.5.2, E.5.3',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Beginning of shift, at least once during an 8 hour shift, before any planned shutdown, at the end of the production, and any time UT machine is interrupted / repaired',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'UT calibration standard',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Weld area, HAZ and mid-wall shall be inspected for longitudinal imperfections. Any signal exceeding alarm threshold limit shall be marked automatically by the marking system of equipment and shall be tested by manual UT. Also Any signal exceeding alarm threshold limit shall be recorded in a chart graph automatically by system. For any weld defect, as per client spec and work instruction for offline UT of the weld, WTL/HFW/QC/WI/10',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'UT report',
      ReferenceStandardAPI: 'API 5L Annex E.5, E.5.5',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '100% weld seam of each pipe(except untested length due to thel imitation of the AUT system)',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Weld Seam Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'For any weld area longitudinal defects as per WI for pipe end ultrasonic testing, WTL/HFW/QC/WI/09. Any indication found greater than acceptance limit in pipe shall be cut-off or rejected',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'MUT report',
      ReferenceStandardAPI: 'API 5L Annex E.3.2.1, E.3.2.3, E.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Each pipe weld length untested by AUT & indications marked by AUT.',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Manual Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Four reading shall be taken ≈ 90° apart around the circumference of each end of the pipe. No one reading shall exceed 25 gauss (3.5 mT) per pipe end when measured with a Hall-effect gauss meter or equivalent values when measured with another type of instrument',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Test report',
      ReferenceStandardAPI: 'API 5L Annex E.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '1 pipes / 4hour shift',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Residual Magnetism',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'The external & internal surfaces of the pipe shall be presented for final visual inspection free of oil, grease, lubricant, flux, loose mill scale or other foreign matter Visual inspection shall include, but not be limited to, the following:\n The entire external surface by an inspector walking the full length of the pipe.\n The internal surface from the pipe ends by an inspector using inspection lamps.\n The pipe ends.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual & Dimension Report',
      ReferenceStandard: 'API 5L CL 10.2.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'WORKMANSHIP, VISUAL INSPECTION AND REPAIR OF DEFECTS',
      TestingFrequency: 'Each pipe inside & outside, pipe ends',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Visual Inspection',
      WTL: 'H',
      Comment: ''
    }
  ],
  [
    {
      AcceptanceCriteriaAPI: 'Steel to be used in the manufacture of the pipes shall be made in basic oxygen or electric arc furnace. The steel shall be continuous cast and fully killed and made according to fine grain practice. The strip shall not contain any repair welds.',
      AcceptanceCriteriaExtracted: 'The seam annealed area shall be cooled \nat an appropriate rate to produce a refined grain microstructure (grain size \n8 or finer).',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: 'API 5L CL 8.38.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coiltfp',
      TestingFrequencyExtracted: '',
      TPI: 'R',
      WorkDescription: 'Steel Coils',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: '',
      AcceptanceCriteriaExtracted: 'Internal slab quality will be measured by macro etch tests rated using the Mannesmann Rating System. For sulfur contents less than or equal to 0.007% the acceptable etching techniques are hot HCL acid, ammonium persulfate or Steltech acid etching. Cold acid etching is not suitable for revealing inclusions. A minimum of one slab macro-etch test shall be performed from the first heat (manufacturing run) of each sequence and every 4th heat thereafter for each casting sequence. Macro- etching shall cover the full width and cross section of the slab. The macro-etched surfaces shall be rated in accordance with the 1-5 Mannesmann Scale and meet the following standards: \n Inclusions - 2 maximum \n Alumina Clouds - 2 maximum \n Transverse Internal Cracks - 2 maximum \n Center Segregation - 2 maximum \n Corner Cracks - 2 maximum \n Macro-etch photographs and/or records and other mill control tests of the slab cross section shall be made available to Purchaser and Company representative for inspection at time of testing.',
      AcceptanceCriteriaTable: [],
      Documents: 'Coil mill test certificate',
      ReferenceStandardAPI: '',
      ReferenceStandardExtracted: 'Client Spec Cl. 4.8.2',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: '',
      TestingFrequencyExtracted: 'A minimum of 3 heats from each casting sequence shall be macro-etch tested or each heat if casting sequence less than 3 heats.',
      TPI: 'R',
      WorkDescription: 'Slab macro-etch',
      WTL: 'R',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Coil Width',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per raw material TDC',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: '',
      ReferenceStandardAPI: 'Raw material TDC',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'Raw Material Review',
      TestingFrequencyAPI: 'Each coil',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Thickness',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Annealing Temperature: Minimum 1600°F so as tosimulate a normalizing heat treatment. More changes.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.8.2',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe(100% weld area)',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Seam Annealing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'As per approved work instruction WTL/HFW/QC/WI/12',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'Approved work instruction',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'On Line UT (Optional)',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Aim A.9.5, adjust as needed to meet A.9.5 after hydro',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Mill report',
      ReferenceStandardAPI: 'API 5L CL 8.9.1',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Random',
      TestingFrequencyExtracted: '',
      TPI: '',
      WorkDescription: 'Pipe Sizing',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'End load compensation is not used.\n If distortion occurs QA/QC will investigate the cause of the distortion.\n Pressure gauge shall be calibrated or checked against an isolated mater gauge at the time of starting of production, after all hydrostatic test bursts and at least once a week during production.\n The tester shall be equipped with a recording gauge that can record the test pressure and the test duration for each length of pipe.\n The test pressure measuring device shall be calibrated by means of a dead-weight tester no more than 4 months prior to each use.',
      AcceptanceCriteriaExtracted: 'Min. Pressure = 2*S*t/D where S = 95% SMYS Duration 10 seconds ',
      AcceptedCriteriaTable: [
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X70M',
          MinP: '3580',
          Hold: '10 sec'
        },
        {
          OD: '20',
          WT: '0.508',
          Gr: 'X65M',
          MinP: '3580',
          Hold: '10 sec'
        }
      ],
      Documents: 'Graph chart showing pressure & holding time for each pipe And test report',
      ReferenceStandardAPI: 'API 5L CL 10.2.6',
      ReferenceStandardExtracted: 'CL 10.2.6',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Hydrostatic Test',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Bevel angle = 30° (+5°, -0°) Root face = 1/16” ± 1/32 (1.6mm±0.8mm)',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual  &Dimension report',
      ReferenceStandardAPI: 'API 5L CL9.12.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plainendpipe',
      Subsection: 'PIPE',
      TestingFrequencyAPI: 'Each pipe',
      TestingFrequencyExtracted: '',
      TPI: 'M',
      WorkDescription: 'Beveling',
      WTL: 'M',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Reference standard shall have the same thickness, same material and same geometry as the pipe being inspected& as per work instruction for offline UT of weld, WTL/HFW/QC/WI/10.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Cal. Report / graph',
      ReferenceStandardAPI: 'API 5L Annex E.5.2, E.5.3',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Beginning of shift, at least once during an 8 hour shift, before any planned shutdown, at the end of the production, and any time UT machine is interrupted / repaired',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'UT calibration standard',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Weld area, HAZ and mid-wall shall be inspected for longitudinal imperfections. Any signal exceeding alarm threshold limit shall be marked automatically by the marking system of equipment and shall be tested by manual UT. Also Any signal exceeding alarm threshold limit shall be recorded in a chart graph automatically by system. For any weld defect, as per client spec and work instruction for offline UT of the weld, WTL/HFW/QC/WI/10',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'UT report',
      ReferenceStandardAPI: 'API 5L Annex E.5, E.5.5',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '100% weld seam of each pipe(except untested length due to thel imitation of the AUT system)',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Weld Seam Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'For any weld area longitudinal defects as per WI for pipe end ultrasonic testing, WTL/HFW/QC/WI/09. Any indication found greater than acceptance limit in pipe shall be cut-off or rejected',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'MUT report',
      ReferenceStandardAPI: 'API 5L Annex E.3.2.1, E.3.2.3, E.5',
      ReferenceStandardExtracted: '',
      Section: 'High frequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: 'Each pipe weld length untested by AUT & indications marked by AUT.',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Manual Ultrasonic Testing',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'Four reading shall be taken ≈ 90° apart around the circumference of each end of the pipe. No one reading shall exceed 25 gauss (3.5 mT) per pipe end when measured with a Hall-effect gauss meter or equivalent values when measured with another type of instrument',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Test report',
      ReferenceStandardAPI: 'API 5L Annex E.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'NDE',
      TestingFrequencyAPI: '1 pipes / 4hour shift',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Residual Magnetism',
      WTL: 'H',
      Comment: ''
    },
    {
      AcceptanceCriteriaAPI: 'The external & internal surfaces of the pipe shall be presented for final visual inspection free of oil, grease, lubricant, flux, loose mill scale or other foreign matter Visual inspection shall include, but not be limited to, the following:\n The entire external surface by an inspector walking the full length of the pipe.\n The internal surface from the pipe ends by an inspector using inspection lamps.\n The pipe ends.',
      AcceptanceCriteriaExtracted: '',
      AcceptanceCriteriaTable: [],
      Documents: 'Visual & Dimension Report',
      ReferenceStandard: 'API 5L CL 10.2.7',
      ReferenceStandardExtracted: '',
      Section: 'Highfrequency welded (HFW) plain end pipe',
      Subsection: 'WORKMANSHIP, VISUAL INSPECTION AND REPAIR OF DEFECTS',
      TestingFrequency: 'Each pipe inside & outside, pipe ends',
      TestingFrequencyExtracted: '',
      TPI: 'RW',
      WorkDescription: 'Visual Inspection',
      WTL: 'H',
      Comment: ''
    }
  ]

]
